version: "3.8"
services:
  # nginx:
  #   build:
  #     context: .
  #     dockerfile: "Dockerfile.nginx"
  #   container_name: booking_nginx
  #   ports:
  #     - 80:80
  #     - 443:443
  #   links:
  #     - booking
  #     - flower

  db:
    image: postgres:15
    container_name: minibank_db
    #volumes:
    #  - postgresdata:/var/lib/postgresql/data
    env_file: # Файл с переменными окружения (Вместо environment)
      - .env-non-dev
    restart: always  
    ports:
      - 5432:5432 # Порт нужен, только если нам нужен доступ к контейнеру напрямую

  
  minibank:
    image: minibank_app
    build:
      context: .
    container_name: minibank_app
    env_file:
      - .env-non-dev
    depends_on: # Запускаем только после запуска БД и Redis (depends on = зависит от)
      - db
      
    # Если не работает эта команда
    command: ["/minibank/docker/app.sh"]
    #command: sh -c "alembic upgrade head && gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 7777:8000
    restart: always













